#pragma once

/*
MetricMonitor
=============

Single-file, header-only C++17 metric and health monitor for UAV/robotics
algorithm modules. It is intentionally independent from ROS message types and
external libraries so it can be dropped into ROS1, ROS2, simulation, or plain
C++ tools.

Features
--------
  - Records four source kinds:
      Header: sequence + timestamp streams such as odometry, sensor frames, or
              planner commands. Calculates loss, latency, frequency, and
              out-of-order count.
      Cost:   numeric streams where smaller is better, such as solve time,
              optimizer cost, or program time cost.
      Score:  numeric streams where larger is better, such as quality score or
              confidence.
      Normal: numeric streams where magnitude has no good/bad direction, such
              as queue size, temperature, or map point count.
  - Uses double UTC seconds since Unix epoch for every timestamp.
  - Uses double seconds for every duration and interval.
  - Producer calls record*() only enqueue data and return quickly.
  - A background thread processes samples asynchronously.
  - Sliding-window statistics:
      Header: total_received_count, total_lost_count, loss_rate,
              total_out_of_order_count, latency min/max/avg, frequency_hz,
              last_sequence.
      Cost:   count, min, max, avg, worst_1_percent_avg where high values are
              worst.
      Score:  count, min, max, avg, worst_1_percent_avg where low values are
              worst.
      Normal: count, min, max, avg, variance, stddev.
  - Availability events:
      NoData:   object or registered metric exists, but no sample arrived after
                no_data_timeout_sec.
      DataLost: at least one sample arrived, but no new sample arrived after
                data_lost_timeout_sec.
  - One fixed-schema metrics CSV containing all calculated metrics and event
    states. A new row is appended when a diagnostics snapshot is generated.
  - One raw CSV file per registered data source, with one row per raw sample.
  - Atomic-style JSON snapshot overwrite under /tmp or another configured
    snapshot directory.
  - Queue overflow policy can drop diagnostic samples instead of blocking flight
    or algorithm callbacks.

Scope And Constraints
---------------------
  - This is a lightweight in-process utility, not a replacement for a full
    observability stack.
  - The core class has no dependency on ROS message types.
  - Producer-facing record*() calls should not calculate statistics, sort data,
    format strings, or write files.
  - Exact real-time guarantees are not claimed, but the producer path is kept
    bounded and predictable for common callback usage.
  - The implementation is header-only and uses only the C++ standard library.

Core Concepts
-------------
  - Metric name:
      Each source is identified by a stable string name, for example "odom",
      "planner_cmd", "mpc_solve_time_ms", "optimizer_final_cost", or
      "trajectory_score". Names should be unique inside one MetricMonitor.
  - MetricKind:
      Module: module-level availability result generated by the monitor itself.
      Header: sequence/timestamp stream.
      Cost:   numeric stream where smaller values are better.
      Score:  numeric stream where larger values are better.
      Normal: numeric stream where value magnitude is neutral.
  - Numeric type handling:
      recordCost(), recordScore(), and recordNormal() accept common arithmetic
      types. Values are converted to double internally to keep storage,
      statistics, CSV, and JSON output simple.
  - Time representation:
      All timestamps are double UTC seconds since Unix epoch. All durations and
      configuration intervals are double seconds.
  - Clock injection:
      MetricMonitorConfig::clock_now_sec may be set by tests or simulations.
      If unset, MetricMonitor uses std::chrono::system_clock converted to
      double UTC epoch seconds.

Design Insights
---------------
  - Register metrics during init when you need fixed CSV columns, raw CSV files,
    or NoData detection before the first sample.
  - finalizeSchema() freezes the CSV schema. After this point, late unregistered
    metrics may still be processed internally, but they will not be added to the
    fixed metrics CSV header or get raw CSV files.
  - start() calls finalizeSchema() automatically if needed.
  - The metrics CSV is a PlotJuggler-friendly wide table:
        time,<metric>/<stat>,<metric>/status/data_lost,...
    It writes the latest known value for every registered signal on each row.
    If a value does not exist yet, missing_value is written.
  - Raw CSV files append every raw sample processed by the background thread.
  - All file I/O and statistics calculations happen on the background thread.
  - latestResults() returns a copy and is safe for callers to inspect.

Statistics
----------
  - Header metrics:
      Input values are sequence, source_timestamp_sec, and receive_time_sec.
      Calculated values are total_received_count, total_lost_count, loss_rate,
      total_out_of_order_count, latency_sec_min, latency_sec_max,
      latency_sec_avg, frequency_hz, and last_sequence.

      Loss calculation:
        if current_sequence > last_sequence + 1:
          total_lost_count += current_sequence - last_sequence - 1
        else if current_sequence <= last_sequence:
          total_out_of_order_count += 1

      Loss rate:
        loss_rate = total_lost_count /
                    (total_lost_count + total_received_count)

      Latency:
        latency_sec = receive_time_sec - source_timestamp_sec

      Both timestamps must share the same UTC epoch representation. If a source
      timestamp uses another clock, convert it before calling recordHeader().

  - Cost metrics:
      Smaller is better. Calculated values are total_count, count, min, max,
      avg, and worst_1_percent_avg. The worst 1 percent are the largest values.

  - Score metrics:
      Larger is better. Calculated values are total_count, count, min, max,
      avg, and worst_1_percent_avg. The worst 1 percent are the smallest values.

  - Normal metrics:
      Direction is neutral. Calculated values are total_count, count, min, max,
      avg, variance, and stddev.

  - 1 percent worst average:
      worst_count = max(1, ceil(N * 0.01))
      Cost metrics average the largest worst_count values.
      Score metrics average the smallest worst_count values.

  - Windowing:
      Statistics are calculated over samples newer than
      now_sec - statistics_window_sec. The monitor also enforces
      max_samples_per_metric to prevent unbounded memory growth.

Status Values
-------------
  - Ok:
      Metric has fresh data and no warning/error threshold violation.
  - Warn:
      Warning threshold violation.
  - Error:
      Error threshold violation. Availability statuses take priority over value
      thresholds.
  - NoData:
      The monitor object or a registered metric exists, but no sample has ever
      been received after no_data_timeout_sec.
  - DataLost:
      At least one sample was received before, but no new sample arrived for
      data_lost_timeout_sec.

  Object-level availability:
    if !has_received_any_data and
       now_sec - monitor_created_time_sec >= no_data_timeout_sec:
      emit module-level NoData
    else if has_received_any_data and
            now_sec - last_any_receive_time_sec >= data_lost_timeout_sec:
      emit module-level DataLost

  Per-metric availability:
    if !has_received_data and now_sec - created_time_sec >= no_data_timeout_sec:
      status = NoData
    else if has_received_data and
            now_sec - last_receive_time_sec >= data_lost_timeout_sec:
      status = DataLost

API Usage
---------
  1. Create a MetricMonitorConfig.
  2. Register all metrics needed in CSV logs and startup NoData detection.
     Header/cost/score registration requires warning and error thresholds.
     Header thresholds are max-latency upper bounds and min-frequency lower
     bounds. Cost thresholds are max value upper bounds. Score thresholds are
     min value lower bounds.
  3. Optionally call finalizeSchema(); start() will call it if you do not.
  4. Call start().
  5. Call recordHeader(), recordCost(), recordScore(), and recordNormal() from
     callbacks or algorithm loops.
  6. Call latestResults() when you need the current calculated state.
  7. Call stop() during shutdown. The destructor also calls stop().

Example
-------
#include <chrono>
#include <iostream>
#include <thread>

#include "metric_monitor.hpp"

int main() {
  using metric_monitor::MetricMonitor;
  using metric_monitor::MetricMonitorConfig;
  using metric_monitor::Status;

  MetricMonitorConfig config;
  config.module_name = "planner_example";
  config.log_directory = "./metric_monitor_logs";
  config.snapshot_directory = "/tmp";
  config.process_interval_sec = 0.02;
  config.metrics_csv_write_interval_sec = 0.5;
  config.tmp_snapshot_write_interval_sec = 0.5;
  config.statistics_window_sec = 5.0;
  config.no_data_timeout_sec = 5.0;
  config.data_lost_timeout_sec = 0.2;

  MetricMonitor monitor(config);
  monitor.registerHeaderMetric(
      "odom",
      0.03,  // warn when max latency is at or above this many seconds
      0.08,  // error when max latency is at or above this many seconds
      40.0,  // warn when frequency is at or below this many Hz
      20.0   // error when frequency is at or below this many Hz
  );
  monitor.registerCostMetric("mpc_solve_time_ms", 4.0, 8.0);
  monitor.registerScoreMetric("trajectory_score", 80.0, 60.0);
  monitor.registerNormalMetric("local_map_points");
  monitor.finalizeSchema();
  monitor.start();

  auto nowSec = [] {
    using Clock = std::chrono::system_clock;
    return std::chrono::duration<double>(Clock::now().time_since_epoch())
        .count();
  };

  {
    // test no data error
    std::this_thread::sleep_for(std::chrono::milliseconds(10000));

    std::cout << "\n\n" << std::endl;
    std::cout << "----------------Test result for no data event----------------"
              << std::endl;
    const auto results = monitor.latestResults();
    for (const auto& result : results) {
      std::cout << result.name
                << " status: " << MetricMonitor::toString(result.status)
                << '\n';
      for (const auto& value : result.values) {
        std::cout << "  " << value.first << ": " << value.second << '\n';
      }
    }
    std::cout << "-------------------------------------------------------------"
              << std::endl;
  }

  for (std::uint64_t i = 0; i < 800; ++i) {
    const double receive_time = nowSec();
    const double source_time = receive_time - 0.01;
    const std::uint64_t sequence =
        i < 40 ? i : i + 1;  // Simulate one lost odom frame.

    monitor.recordHeader("odom", sequence, source_time);
    monitor.recordCost("mpc_solve_time_ms",
                       2.0 + static_cast<double>(i % 7) * 0.25);
    monitor.recordScore("trajectory_score", 100.0 - static_cast<double>(i % 5));
    monitor.recordNormal("local_map_points", 5000 + static_cast<int>(i % 20));

    std::this_thread::sleep_for(std::chrono::milliseconds(20));

    if (i == 100) {
      std::cout << "\n\n" << std::endl;
      std::cout
          << "---------------- Test result for normal event----------------"
          << std::endl;
      const auto results = monitor.latestResults();
      for (const auto& result : results) {
        std::cout << result.name
                  << " status: " << MetricMonitor::toString(result.status)
                  << '\n';
        for (const auto& value : result.values) {
          std::cout << "  " << value.first << ": " << value.second << '\n';
        }
      }
      std::cout
          << "-------------------------------------------------------------"
          << std::endl;
    }
  }

  // test data lost error
  std::this_thread::sleep_for(std::chrono::milliseconds(600));
  std::cout << "\n\n" << std::endl;
  std::cout << "---------------Test result for data lost event---------------"
            << std::endl;
  const auto results = monitor.latestResults();
  for (const auto& result : results) {
    std::cout << result.name
              << " status: " << MetricMonitor::toString(result.status) << '\n';
    for (const auto& value : result.values) {
      std::cout << "  " << value.first << ": " << value.second << '\n';
    }
  }
  std::cout << "-------------------------------------------------------------"
            << std::endl;

  monitor.stop();

  std::cout << "CSV logs written under ./metric_monitor_logs\n";
  std::cout << "JSON snapshot written to "
               "/tmp/planner_example_metrics_snapshot.json\n";
  return 0;
}



ROS Timestamp Adapter
---------------------
  Keep ROS-specific types outside the core class. Convert ROS timestamps to
  double UTC seconds before calling recordHeader().

  inline double rosStampToSec(int64_t sec, uint32_t nsec) {
    return static_cast<double>(sec) + static_cast<double>(nsec) * 1e-9;
  }

Output Files
------------
  Metrics CSV:
    <log_directory>/<module_name>_<YYYYMMDD_HHMMSS>_metrics.csv

    The first line is fixed after finalizeSchema(). Rows are appended at
    metrics_csv_write_interval_sec.

    Layout:
      time,<signal_1>,<signal_2>,...

    Rules:
      - The first column is always time, using double UTC epoch seconds.
      - Every other column is numeric.
      - Signal names are path-like, for example odom/loss_rate or
        mpc_solve_time_ms/avg.
      - New columns are not added after data rows have started.
      - Each row contains the latest known value for every registered signal.
      - Missing values are written as missing_value.
      - String messages are not written to CSV.
      - Status values are encoded as 0/1 status columns:
          <metric>/status/ok
          <metric>/status/warn
          <metric>/status/error
          <metric>/status/no_data
          <metric>/status/data_lost

  Raw source CSV:
    <log_directory>/<module_name>_<YYYYMMDD_HHMMSS>_<source_name>_raw.csv

    One file is created for each registered data source. One row is appended
    for every raw sample processed by the background thread.

    Header stream layout:
      time,source_timestamp_sec,receive_time_sec,sequence,latency_sec

    Numeric stream layout:
      time,receive_time_sec,value

  JSON snapshot:
    <snapshot_directory>/<module_name>_metrics_snapshot.json

    The file is overwritten through a temporary file + rename pattern at
    tmp_snapshot_write_interval_sec. Missing/non-finite numeric values are
    written as null so strict JSON loaders can parse the file.

    Shape:
      {
        "module": "...",
        "wall_time_sec": 1781600000.0,
        "results": [
          {
            "name": "...",
            "kind": "cost",
            "status": "ok",
            "message": "...",
            "values": { "avg": 3.4 }
          }
        ]
      }

Operational Notes
-----------------
  - Use UTC/system time consistently for both source_timestamp_sec and internal
    receive time if you care about latency.
  - For source timestamps that are not comparable to UTC epoch time, latency is
    not meaningful without an adapter.
  - The default missing_value is NaN, which PlotJuggler and many analysis tools
    can treat as missing data.
  - drop_when_queue_full=true is recommended for flight/control paths because
    diagnostics should not block core algorithms.
  - Duplicate metric registrations are ignored.
  - MetricThreshold stores warning/error thresholds configured at registration.
    Header uses latency_sec_max as an upper bound and frequency_hz as a lower
    bound. Cost uses max as an upper bound, and score uses min as a lower
    bound. Availability statuses still take priority.

Testing Guidance
----------------
  Useful unit tests:
    - Cost metric min, max, average, and largest 1 percent average.
    - Score metric smallest 1 percent average.
    - Normal metric variance and standard deviation.
    - Header sequence loss and out-of-order detection.
    - Registered metric NoData timeout.
    - Previously active metric DataLost timeout.
    - Sliding-window trimming.
    - Queue overflow behavior.
    - Valid JSON snapshot output.
    - Metrics CSV appends one full snapshot row.
    - Raw CSV appends one row for every valid raw sample.
    - start() and stop() idempotency.

  Useful runtime checks:
    - Record from a high-frequency loop and confirm callback latency remains
      stable.
    - Load metrics/raw CSV files in PlotJuggler.
    - Run with an unwritable log directory and confirm the algorithm continues.
    - Kill and restart a dashboard reading the /tmp snapshot.

Extensibility
-------------
  Future metric kinds can be added by extending:
    - MetricKind
    - QueuedSample payload
    - A kind-specific state struct
    - A kind-specific statistics function
    - CSV/JSON serialization of the new kind

  Keep public record*() methods small wrappers around enqueue(). This preserves
  the low-overhead producer path while allowing the background thread to own all
  new aggregation and file-output behavior.

  Useful future extensions:
    - Histogram metrics.
    - Event counters.
    - Boolean state metrics.
    - String/status metrics in JSON snapshots.
    - More per-metric MetricThreshold options beyond the current registration
      thresholds.
    - Lock-free MPSC queue if profiling shows the mutex queue is too expensive.
    - Optional JSON-lines or key/value debug logs beside the PlotJuggler CSVs.
    - Count-window statistics in addition to the current time-window statistics.
    - Welford variance and nth_element worst-percent calculations for very
      large windows.
    - YAML, ROS parameter, or direct C++ API threshold configuration.

Error Handling
--------------
  - File open/write failures should not throw through the processing thread.
    This implementation stores an internal error message and continues running.
  - Invalid numeric values such as NaN and Inf are ignored for numeric streams.
  - start() and stop() are idempotent.
  - The destructor calls stop().
  - If the pending queue is full and drop_when_queue_full is true, the new
    diagnostic sample is dropped and dropped_sample_count is incremented.
  - If drop_when_queue_full is false, the queue may grow beyond
    max_pending_samples; use this mode only when diagnostics must be retained
    and callback latency is less important.

Compile Example
---------------
  g++ -std=c++17 -O2 -Wall -Wextra -pedantic example.cpp -pthread -o
metric_monitor_example
*/

#include <algorithm>
#include <atomic>
#include <chrono>
#include <cmath>
#include <condition_variable>
#include <cstdint>
#include <cstdio>
#include <ctime>
#include <deque>
#include <exception>
#include <filesystem>
#include <fstream>
#include <functional>
#include <iomanip>
#include <iostream>
#include <limits>
#include <map>
#include <mutex>
#include <numeric>
#include <optional>
#include <sstream>
#include <string>
#include <thread>
#include <unordered_map>
#include <utility>
#include <vector>

#define __METRIC_LIB_VERSION__ __20260715__

namespace metric_monitor {

using TimestampSec = double;
using DurationSec = double;

// Describes how a stream should be interpreted and which statistics to compute.
enum class MetricKind { Module, Header, Cost, Score, Normal };

// Availability and threshold state reported for each MetricResult.
enum class Status { Ok, Warn, Error, NoData, DataLost };

struct MetricMonitorConfig {
  // Logical owner name. Used in file names and module-level availability rows.
  std::string module_name = "default";

  // Persistent CSV output directory and short-lived JSON snapshot directory.
  std::string log_directory = "./metrics_logs";
  std::string snapshot_directory = "/tmp";

  // Background worker cadence.
  double process_interval_sec = 0.1;

  // Periodic output cadences.
  double metrics_csv_write_interval_sec = 1.0;
  double tmp_snapshot_write_interval_sec = 0.5;

  // Sliding-window and availability settings.
  double statistics_window_sec = 10.0;
  double no_data_timeout_sec = 2.0;
  double data_lost_timeout_sec = 1.0;

  // Queue/window bounds. Dropping diagnostic samples is usually preferable to
  // blocking algorithm callbacks.
  std::size_t max_pending_samples = 10000;
  std::size_t max_samples_per_metric = 10000;

  bool drop_when_queue_full = true;

  // Output controls.
  bool write_metrics_csv = true;
  bool write_raw_csv = true;
  bool write_tmp_json_snapshot = true;

  // Placeholder for fixed-schema CSV columns that do not have a value yet.
  double missing_value = std::numeric_limits<double>::quiet_NaN();

  // Optional test/simulation clock. Must return UTC seconds since Unix epoch.
  std::function<double()> clock_now_sec;
};

// Reserved extension point for future warning/error thresholds.
struct MetricThreshold {
  std::optional<double> warn_if_above;
  std::optional<double> error_if_above;
  std::optional<double> warn_if_below;
  std::optional<double> error_if_below;
};

// Public result snapshot for one metric or module-level availability state.
struct MetricResult {
  std::string name;
  MetricKind kind = MetricKind::Normal;
  Status status = Status::Ok;
  double update_time_sec = 0.0;
  std::map<std::string, double> values;
  std::string message;
};

class MetricMonitor {
 public:
  explicit MetricMonitor(MetricMonitorConfig config)
      : config_(std::move(config)) {
    if (!config_.clock_now_sec) {
      config_.clock_now_sec = [] {
        using Clock = std::chrono::system_clock;
        const auto now = Clock::now().time_since_epoch();
        return std::chrono::duration<double>(now).count();
      };
    }
    created_time_sec_ = nowSec();
    last_metrics_csv_write_sec_ = created_time_sec_;
    last_tmp_snapshot_write_sec_ = created_time_sec_;
  }

  ~MetricMonitor() { stop(); }

  MetricMonitor(const MetricMonitor&) = delete;
  MetricMonitor& operator=(const MetricMonitor&) = delete;

  static const char* toString(MetricKind kind) {
    switch (kind) {
      case MetricKind::Module:
        return "module";
      case MetricKind::Header:
        return "header";
      case MetricKind::Cost:
        return "cost";
      case MetricKind::Score:
        return "score";
      case MetricKind::Normal:
        return "normal";
    }
    return "unknown";
  }

  static const char* toString(Status status) {
    switch (status) {
      case Status::Ok:
        return "ok";
      case Status::Warn:
        return "warn";
      case Status::Error:
        return "error";
      case Status::NoData:
        return "no_data";
      case Status::DataLost:
        return "data_lost";
    }
    return "unknown";
  }

  // Starts the background worker. Safe to call more than once.
  void start() {
    bool expected = false;
    if (!running_.compare_exchange_strong(expected, true)) {
      return;
    }
    finalizeSchema();
    worker_ = std::thread(&MetricMonitor::processLoop, this);
  }

  // Stops the worker, drains remaining queued samples, and flushes files.
  void stop() {
    bool expected = true;
    if (!running_.compare_exchange_strong(expected, false)) {
      return;
    }
    queue_cv_.notify_all();
    if (worker_.joinable()) {
      worker_.join();
    }
    flushFiles();
  }

  // Registration is required for fixed CSV columns, raw CSV files, and startup
  // NoData detection. Header latency thresholds are max-latency upper bounds;
  // frequency thresholds are min-frequency lower bounds.
  void registerHeaderMetric(const std::string& name,
                            double max_latency_warn_threshold_sec,
                            double max_latency_error_threshold_sec,
                            double min_frequency_warn_threshold_hz,
                            double min_frequency_error_threshold_hz) {
    std::lock_guard<std::mutex> lock(state_mutex_);
    if (finalized_) {
      return;
    }
    if (isRegisteredLocked(name)) {
      return;
    }
    registered_order_.push_back({name, MetricKind::Header});
    auto& state = header_states_[name];
    state.created_time_sec = created_time_sec_;
    state.latency_threshold.warn_if_above = max_latency_warn_threshold_sec;
    state.latency_threshold.error_if_above = max_latency_error_threshold_sec;
    state.frequency_threshold.warn_if_below = min_frequency_warn_threshold_hz;
    state.frequency_threshold.error_if_below = min_frequency_error_threshold_hz;
  }

  void registerCostMetric(const std::string& name, double warning_threshold,
                          double error_threshold) {
    registerNumericMetric(name, MetricKind::Cost, warning_threshold,
                          error_threshold);
  }

  void registerScoreMetric(const std::string& name, double warning_threshold,
                           double error_threshold) {
    registerNumericMetric(name, MetricKind::Score, warning_threshold,
                          error_threshold);
  }

  void registerNormalMetric(const std::string& name) {
    std::lock_guard<std::mutex> lock(state_mutex_);
    if (finalized_) {
      return;
    }
    if (isRegisteredLocked(name)) {
      return;
    }
    registered_order_.push_back({name, MetricKind::Normal});
    auto& state = numeric_states_[name];
    state.kind = MetricKind::Normal;
    state.created_time_sec = created_time_sec_;
  }

  // Freezes the CSV schema and opens output files. start() calls this
  // automatically if the user has not called it.
  void finalizeSchema() {
    std::lock_guard<std::mutex> lock(state_mutex_);
    if (finalized_) {
      return;
    }
    finalized_ = true;

    base_file_stem_ =
        config_.module_name + "_" + makeDateStamp(created_time_sec_);
    createDirectory(config_.log_directory);
    createDirectory(config_.snapshot_directory);

    buildMetricsColumnsLocked();
    openMetricsCsvLocked();
    openRawCsvFilesLocked();
  }

  // Records one sequence/timestamp sample. source_timestamp_sec must use the
  // same UTC epoch basis as the monitor clock if latency is meaningful.
  void recordHeader(const std::string& name, std::uint64_t sequence,
                    double source_timestamp_sec) {
    QueuedSample sample;
    sample.kind = MetricKind::Header;
    sample.name = name;
    sample.receive_time_sec = nowSec();
    sample.sequence = sequence;
    sample.source_timestamp_sec = source_timestamp_sec;
    enqueue(std::move(sample));
  }

  template <typename T>
  void recordCost(const std::string& name, T value) {
    recordNumeric(name, MetricKind::Cost, value);
  }

  template <typename T>
  void recordScore(const std::string& name, T value) {
    recordNumeric(name, MetricKind::Score, value);
  }

  template <typename T>
  void recordNormal(const std::string& name, T value) {
    recordNumeric(name, MetricKind::Normal, value);
  }

  // Returns a copy so callers never observe partially updated result state.
  std::vector<MetricResult> latestResults() const {
    std::lock_guard<std::mutex> lock(results_mutex_);
    return latest_results_;
  }

 private:
  // Producer threads write this compact representation into pending_samples_.
  // The worker thread is the only consumer.
  struct QueuedSample {
    MetricKind kind = MetricKind::Normal;
    std::string name;
    double receive_time_sec = 0.0;
    std::optional<double> numeric_value;
    std::optional<std::uint64_t> sequence;
    std::optional<double> source_timestamp_sec;
  };

  // Raw header sample kept for the sliding statistics window and raw CSV
  // output.
  struct HeaderSample {
    std::uint64_t sequence = 0;
    double source_timestamp_sec = 0.0;
    double receive_time_sec = 0.0;
  };

  // Raw numeric sample kept for cost/score/normal windows.
  struct NumericSample {
    double value = 0.0;
    double receive_time_sec = 0.0;
  };

  // Full state for one Header stream. Totals are lifetime counters; window is
  // trimmed by statistics_window_sec and max_samples_per_metric.
  struct HeaderMetricState {
    double created_time_sec = 0.0;
    double last_receive_time_sec = 0.0;
    bool has_received_data = false;
    bool has_last_sequence = false;
    std::uint64_t last_sequence = 0;
    std::uint64_t total_received_count = 0;
    std::uint64_t total_lost_count = 0;
    std::uint64_t total_out_of_order_count = 0;
    std::deque<HeaderSample> window;
    MetricThreshold latency_threshold;
    MetricThreshold frequency_threshold;

    HeaderSample latest_sample;
    bool has_latest_sample = false;
  };

  // Full state for one Cost, Score, or Normal stream.
  struct NumericMetricState {
    MetricKind kind = MetricKind::Normal;
    double created_time_sec = 0.0;
    double last_receive_time_sec = 0.0;
    bool has_received_data = false;
    std::deque<NumericSample> window;
    std::uint64_t total_count = 0;
    MetricThreshold threshold;

    NumericSample latest_sample;
    bool has_latest_sample = false;
  };

  // Owns one raw CSV stream and the stream kind needed to choose row format.
  struct RawCsvFile {
    MetricKind kind = MetricKind::Normal;
    std::ofstream stream;
  };

  // One fixed metrics CSV column. The header is built once in finalizeSchema().
  struct Column {
    std::string metric_name;
    MetricKind kind = MetricKind::Normal;
    std::string key;
    std::string csv_name;
  };

  // Preserves user registration order for stable CSV column and raw-file order.
  struct RegisteredMetric {
    std::string name;
    MetricKind kind = MetricKind::Normal;
  };

  double nowSec() const {
    return config_.clock_now_sec ? config_.clock_now_sec() : 0.0;
  }

  static std::chrono::duration<double> secondsToDuration(double seconds) {
    return std::chrono::duration<double>(std::max(0.001, seconds));
  }

  static bool isFinite(double value) { return std::isfinite(value); }

  static std::string sanitizeName(const std::string& input) {
    std::string out;
    out.reserve(input.size());
    for (char c : input) {
      const bool ok = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
                      (c >= '0' && c <= '9') || c == '_' || c == '-' ||
                      c == '/' || c == '.';
      out.push_back(ok ? c : '_');
    }
    return out.empty() ? "unnamed" : out;
  }

  static std::string sanitizeFileName(const std::string& input) {
    std::string out = sanitizeName(input);
    std::replace(out.begin(), out.end(), '/', '_');
    return out;
  }

  static std::string makeDateStamp(double timestamp_sec) {
    const auto tt = static_cast<std::time_t>(timestamp_sec);
    std::tm tm{};
#if defined(_WIN32)
    localtime_s(&tm, &tt);
#else
    localtime_r(&tt, &tm);
#endif
    std::ostringstream oss;
    oss << std::put_time(&tm, "%Y%m%d_%H%M%S");
    return oss.str();
  }

  static std::string formatDouble(double value) {
    if (std::isnan(value)) {
      return "nan";
    }
    if (std::isinf(value)) {
      return value > 0.0 ? "inf" : "-inf";
    }
    std::ostringstream oss;
    oss << std::fixed << std::setprecision(9) << value;
    return oss.str();
  }

  static std::string formatJsonNumber(double value) {
    if (!std::isfinite(value)) {
      return "null";
    }
    return formatDouble(value);
  }

  static std::string jsonEscape(const std::string& input) {
    std::ostringstream oss;
    for (char c : input) {
      switch (c) {
        case '"':
          oss << "\\\"";
          break;
        case '\\':
          oss << "\\\\";
          break;
        case '\n':
          oss << "\\n";
          break;
        case '\r':
          oss << "\\r";
          break;
        case '\t':
          oss << "\\t";
          break;
        default:
          oss << c;
          break;
      }
    }
    return oss.str();
  }

  static void createDirectory(const std::string& path) {
    if (path.empty()) {
      return;
    }
    std::error_code ec;
    std::filesystem::create_directories(path, ec);
  }

  static std::string absolutePath(const std::string& path) {
    std::error_code ec;
    const auto absolute = std::filesystem::absolute(path, ec);
    return ec ? path : absolute.lexically_normal().string();
  }

  template <typename T>
  void recordNumeric(const std::string& name, MetricKind kind, T value) {
    QueuedSample sample;
    sample.kind = kind;
    sample.name = name;
    sample.receive_time_sec = nowSec();
    sample.numeric_value = static_cast<double>(value);
    enqueue(std::move(sample));
  }

  // Shared implementation behind registerCostMetric/registerScoreMetric.
  // Cost thresholds are upper bounds; score thresholds are lower bounds.
  void registerNumericMetric(const std::string& name, MetricKind kind,
                             double warning_threshold, double error_threshold) {
    std::lock_guard<std::mutex> lock(state_mutex_);
    if (finalized_) {
      return;
    }
    if (isRegisteredLocked(name)) {
      return;
    }
    registered_order_.push_back({name, kind});
    auto& state = numeric_states_[name];
    state.kind = kind;
    state.created_time_sec = created_time_sec_;
    if (kind == MetricKind::Score) {
      state.threshold.warn_if_below = warning_threshold;
      state.threshold.error_if_below = error_threshold;
    } else {
      state.threshold.warn_if_above = warning_threshold;
      state.threshold.error_if_above = error_threshold;
    }
  }

  // The only function called by producer-facing record*() methods after they
  // package a sample. It intentionally does no statistics or file I/O.
  void enqueue(QueuedSample sample) {
    std::lock_guard<std::mutex> lock(queue_mutex_);
    if (pending_samples_.size() >= config_.max_pending_samples) {
      if (config_.drop_when_queue_full) {
        ++dropped_sample_count_;
        return;
      }
    }
    pending_samples_.push_back(std::move(sample));
    queue_cv_.notify_one();
  }

  bool isRegisteredLocked(const std::string& name) const {
    return std::any_of(
        registered_order_.begin(), registered_order_.end(),
        [&](const RegisteredMetric& item) { return item.name == name; });
  }

  // Worker thread main loop: drain queue, update state/results, and perform
  // periodic file output. state_mutex_ is held only for the processing phase.
  void processLoop() {
    try {
      while (running_.load()) {
        std::vector<QueuedSample> batch;
        {
          std::unique_lock<std::mutex> lock(queue_mutex_);
          queue_cv_.wait_for(
              lock, secondsToDuration(config_.process_interval_sec),
              [&] { return !running_.load() || !pending_samples_.empty(); });
          drainPendingSamplesLocked(batch);
        }

        const double now = nowSec();
        {
          std::lock_guard<std::mutex> lock(state_mutex_);
          processBatchLocked(batch);
          trimOldSamplesLocked(now);
          updateMetricResultsLocked(now);
          maybeAppendMetricsCsvRowLocked(now);
          maybeWriteTmpSnapshotFileLocked(now);
        }
      }

      // Shutdown path: after running_ becomes false, drain anything that was
      // queued before stop() woke the worker. The normal loop may exit before
      // the final samples are processed, so this preserves the last data points
      // and writes one final metrics/raw/JSON snapshot.
      std::vector<QueuedSample> batch;
      {
        std::lock_guard<std::mutex> lock(queue_mutex_);
        drainPendingSamplesLocked(batch);
      }
      const double now = nowSec();
      {
        std::lock_guard<std::mutex> lock(state_mutex_);
        processBatchLocked(batch);
        trimOldSamplesLocked(now);
        updateMetricResultsLocked(now);
        appendMetricsCsvRowLocked(now);
        writeTmpSnapshotFileLocked(now);
      }
    } catch (const std::exception& e) {
      std::lock_guard<std::mutex> lock(state_mutex_);
      internal_error_message_ =
          std::string("processLoop exception: ") + e.what();
    } catch (...) {
      std::lock_guard<std::mutex> lock(state_mutex_);
      internal_error_message_ = "processLoop unknown exception";
    }
  }

  // Moves all pending samples into a local batch while queue_mutex_ is held.
  void drainPendingSamplesLocked(std::vector<QueuedSample>& batch) {
    batch.reserve(batch.size() + pending_samples_.size());
    while (!pending_samples_.empty()) {
      batch.push_back(std::move(pending_samples_.front()));
      pending_samples_.pop_front();
    }
  }

  // Applies a drained batch to per-metric states. state_mutex_ must be held.
  void processBatchLocked(const std::vector<QueuedSample>& batch) {
    for (const auto& sample : batch) {
      has_received_any_data_ = true;
      last_any_receive_time_sec_ = sample.receive_time_sec;

      if (sample.kind == MetricKind::Header) {
        processHeaderSampleLocked(sample);
      } else {
        processNumericSampleLocked(sample);
      }
    }
  }

  // Updates sequence loss counters and the latency/frequency window.
  void processHeaderSampleLocked(const QueuedSample& sample) {
    if (!sample.sequence || !sample.source_timestamp_sec) {
      return;
    }

    auto& state = header_states_[sample.name];
    if (state.created_time_sec <= 0.0) {
      state.created_time_sec = sample.receive_time_sec;
    }
    state.has_received_data = true;
    state.last_receive_time_sec = sample.receive_time_sec;
    ++state.total_received_count;

    const std::uint64_t sequence = *sample.sequence;
    if (state.has_last_sequence) {
      if (sequence > state.last_sequence + 1) {
        state.total_lost_count += sequence - state.last_sequence - 1;
      } else if (sequence <= state.last_sequence) {
        ++state.total_out_of_order_count;
      }
    }
    if (!state.has_last_sequence || sequence > state.last_sequence) {
      state.last_sequence = sequence;
      state.has_last_sequence = true;
    }

    HeaderSample raw;
    raw.sequence = sequence;
    raw.source_timestamp_sec = *sample.source_timestamp_sec;
    raw.receive_time_sec = sample.receive_time_sec;
    state.window.push_back(raw);
    state.latest_sample = raw;
    state.has_latest_sample = true;
    appendHeaderRawSampleLocked(sample.name, raw);
  }

  // Ignores non-finite values so NaN/Inf do not poison numeric statistics.
  void processNumericSampleLocked(const QueuedSample& sample) {
    if (!sample.numeric_value || !isFinite(*sample.numeric_value)) {
      return;
    }

    auto& state = numeric_states_[sample.name];
    if (state.created_time_sec <= 0.0) {
      state.created_time_sec = sample.receive_time_sec;
    }
    state.kind = sample.kind;
    state.has_received_data = true;
    state.last_receive_time_sec = sample.receive_time_sec;
    ++state.total_count;

    NumericSample raw;
    raw.value = *sample.numeric_value;
    raw.receive_time_sec = sample.receive_time_sec;
    state.window.push_back(raw);
    state.latest_sample = raw;
    state.has_latest_sample = true;
    appendNumericRawSampleLocked(sample.name, raw);
  }

  // Keeps the sliding windows bounded by time and count.
  void trimOldSamplesLocked(double now) {
    const double cutoff = now - config_.statistics_window_sec;
    for (auto& item : header_states_) {
      auto& window = item.second.window;
      while (!window.empty() && window.front().receive_time_sec < cutoff) {
        window.pop_front();
      }
      while (window.size() > config_.max_samples_per_metric) {
        window.pop_front();
      }
    }
    for (auto& item : numeric_states_) {
      auto& window = item.second.window;
      while (!window.empty() && window.front().receive_time_sec < cutoff) {
        window.pop_front();
      }
      while (window.size() > config_.max_samples_per_metric) {
        window.pop_front();
      }
    }
  }

  // Rebuilds latest_results_ from current state. latest_results_cache_ is the
  // worker-owned copy used by CSV/JSON writers.
  void updateMetricResultsLocked(double now) {
    std::vector<MetricResult> results;
    results.push_back(makeModuleResultLocked(now));

    for (const auto& item : header_states_) {
      results.push_back(makeHeaderResult(item.first, item.second, now));
    }
    for (const auto& item : numeric_states_) {
      results.push_back(makeNumericResult(item.first, item.second, now));
    }

    {
      std::lock_guard<std::mutex> lock(results_mutex_);
      latest_results_ = results;
    }
    latest_results_cache_ = std::move(results);
  }

  // Availability is computed before threshold semantics; missing/stopped data
  // should dominate any value-based interpretation.
  Status availabilityStatus(bool has_data, double created_time_sec,
                            double last_receive_time_sec, double now) const {
    if (!has_data && now - created_time_sec >= config_.no_data_timeout_sec) {
      return Status::NoData;
    }
    if (has_data &&
        now - last_receive_time_sec >= config_.data_lost_timeout_sec) {
      return Status::DataLost;
    }
    return Status::Ok;
  }

  Status applyThresholdStatus(Status current, double value,
                              const MetricThreshold& threshold) const {
    if (current == Status::NoData || current == Status::DataLost ||
        !isFinite(value)) {
      return current;
    }
    if (threshold.error_if_above && value >= *threshold.error_if_above) {
      return Status::Error;
    }
    if (threshold.error_if_below && value <= *threshold.error_if_below) {
      return Status::Error;
    }
    if (current == Status::Warn) {
      return current;
    }
    if (threshold.warn_if_above && value >= *threshold.warn_if_above) {
      return Status::Warn;
    }
    if (threshold.warn_if_below && value <= *threshold.warn_if_below) {
      return Status::Warn;
    }
    return current;
  }

  // Synthetic result for object-level NoData/DataLost and queue drops.
  MetricResult makeModuleResultLocked(double now) const {
    MetricResult result;
    result.name = config_.module_name;
    result.kind = MetricKind::Module;
    result.update_time_sec = now;
    result.status =
        availabilityStatus(has_received_any_data_, created_time_sec_,
                           last_any_receive_time_sec_, now);
    result.values["monitor_created_time_sec"] = created_time_sec_;
    result.values["last_any_receive_time_sec"] =
        has_received_any_data_ ? last_any_receive_time_sec_
                               : config_.missing_value;
    result.values["time_since_create_sec"] = now - created_time_sec_;
    result.values["time_since_last_any_receive_sec"] =
        has_received_any_data_ ? now - last_any_receive_time_sec_
                               : config_.missing_value;
    result.values["dropped_sample_count"] =
        static_cast<double>(dropped_sample_count_.load());
    result.message = toString(result.status);
    return result;
  }

  // Builds the public result for one sequence/timestamp stream.
  MetricResult makeHeaderResult(const std::string& name,
                                const HeaderMetricState& state,
                                double now) const {
    MetricResult result;
    result.name = name;
    result.kind = MetricKind::Header;
    result.update_time_sec = now;
    result.status =
        availabilityStatus(state.has_received_data, state.created_time_sec,
                           state.last_receive_time_sec, now);
    result.message = toString(result.status);

    result.values["total_received_count"] =
        static_cast<double>(state.total_received_count);
    result.values["total_lost_count"] =
        static_cast<double>(state.total_lost_count);
    result.values["total_out_of_order_count"] =
        static_cast<double>(state.total_out_of_order_count);
    const double denom = static_cast<double>(state.total_lost_count +
                                             state.total_received_count);
    result.values["loss_rate"] =
        denom > 0.0 ? static_cast<double>(state.total_lost_count) / denom : 0.0;
    result.values["last_sequence"] =
        state.has_last_sequence ? static_cast<double>(state.last_sequence)
                                : config_.missing_value;
    addAvailabilityValues(result, state.created_time_sec,
                          state.last_receive_time_sec, state.has_received_data,
                          now);

    if (state.window.empty()) {
      result.values["latency_sec_min"] = config_.missing_value;
      result.values["latency_sec_max"] = config_.missing_value;
      result.values["latency_sec_avg"] = config_.missing_value;
      result.values["frequency_hz"] = 0.0;
      return result;
    }

    double min_latency = std::numeric_limits<double>::infinity();
    double max_latency = -std::numeric_limits<double>::infinity();
    double sum_latency = 0.0;
    for (const auto& sample : state.window) {
      const double latency =
          sample.receive_time_sec - sample.source_timestamp_sec;
      min_latency = std::min(min_latency, latency);
      max_latency = std::max(max_latency, latency);
      sum_latency += latency;
    }
    result.values["latency_sec_min"] = min_latency;
    result.values["latency_sec_max"] = max_latency;
    result.values["latency_sec_avg"] =
        sum_latency / static_cast<double>(state.window.size());
    result.values["frequency_hz"] = headerFrequency(state.window);
    result.status =
        applyThresholdStatus(result.status, result.values["latency_sec_max"],
                             state.latency_threshold);
    result.status =
        applyThresholdStatus(result.status, result.values["frequency_hz"],
                             state.frequency_threshold);
    result.message = toString(result.status);
    return result;
  }

  // Builds the public result for one numeric stream.
  MetricResult makeNumericResult(const std::string& name,
                                 const NumericMetricState& state,
                                 double now) const {
    MetricResult result;
    result.name = name;
    result.kind = state.kind;
    result.update_time_sec = now;
    result.status =
        availabilityStatus(state.has_received_data, state.created_time_sec,
                           state.last_receive_time_sec, now);
    result.message = toString(result.status);
    result.values["total_count"] = static_cast<double>(state.total_count);
    addAvailabilityValues(result, state.created_time_sec,
                          state.last_receive_time_sec, state.has_received_data,
                          now);

    if (state.window.empty()) {
      result.values["count"] = 0.0;
      result.values["min"] = config_.missing_value;
      result.values["max"] = config_.missing_value;
      result.values["avg"] = config_.missing_value;
      if (state.kind == MetricKind::Normal) {
        result.values["variance"] = config_.missing_value;
        result.values["stddev"] = config_.missing_value;
      } else {
        result.values["worst_1_percent_avg"] = config_.missing_value;
      }
      return result;
    }

    std::vector<double> values;
    values.reserve(state.window.size());
    for (const auto& sample : state.window) {
      values.push_back(sample.value);
    }

    const auto minmax = std::minmax_element(values.begin(), values.end());
    const double sum = std::accumulate(values.begin(), values.end(), 0.0);
    const double avg = sum / static_cast<double>(values.size());

    result.values["count"] = static_cast<double>(values.size());
    result.values["min"] = *minmax.first;
    result.values["max"] = *minmax.second;
    result.values["avg"] = avg;

    if (state.kind == MetricKind::Normal) {
      double variance_sum = 0.0;
      for (double value : values) {
        const double delta = value - avg;
        variance_sum += delta * delta;
      }
      const double variance = variance_sum / static_cast<double>(values.size());
      result.values["variance"] = variance;
      result.values["stddev"] = std::sqrt(variance);
    } else {
      result.values["worst_1_percent_avg"] =
          worstOnePercentAverage(values, state.kind == MetricKind::Cost);
      const double threshold_value = state.kind == MetricKind::Cost
                                         ? result.values["max"]
                                         : result.values["min"];
      result.status =
          applyThresholdStatus(result.status, threshold_value, state.threshold);
      result.message = toString(result.status);
    }

    return result;
  }

  // Adds common per-metric availability values to every non-module result.
  void addAvailabilityValues(MetricResult& result, double created_time_sec,
                             double last_receive_time_sec,
                             bool has_received_data, double now) const {
    result.values["created_time_sec"] = created_time_sec;
    result.values["last_receive_time_sec"] =
        has_received_data ? last_receive_time_sec : config_.missing_value;
    result.values["time_since_create_sec"] = now - created_time_sec;
    result.values["time_since_last_receive_sec"] =
        has_received_data ? now - last_receive_time_sec : config_.missing_value;
  }

  // Frequency is based on receive timestamps inside the current statistics
  // window, not on sequence numbers.
  static double headerFrequency(const std::deque<HeaderSample>& window) {
    if (window.size() < 2) {
      return 0.0;
    }
    const double duration =
        window.back().receive_time_sec - window.front().receive_time_sec;
    if (duration <= 0.0) {
      return 0.0;
    }
    return static_cast<double>(window.size() - 1) / duration;
  }

  // For cost high values are bad; for score low values are bad.
  static double worstOnePercentAverage(std::vector<double> values,
                                       bool high_is_bad) {
    if (values.empty()) {
      return std::numeric_limits<double>::quiet_NaN();
    }
    const std::size_t count = std::max<std::size_t>(
        1, static_cast<std::size_t>(std::ceil(values.size() * 0.01)));
    if (high_is_bad) {
      std::sort(values.begin(), values.end(), std::greater<double>());
    } else {
      std::sort(values.begin(), values.end());
    }
    const double sum =
        std::accumulate(values.begin(), values.begin() + count, 0.0);
    return sum / static_cast<double>(count);
  }

  // Constructs the fixed all-metrics CSV schema from registered metrics.
  void buildMetricsColumnsLocked() {
    metrics_columns_.clear();
    addStatusColumns(config_.module_name, MetricKind::Module);
    addColumn(config_.module_name, MetricKind::Module, "time_since_create_sec");
    addColumn(config_.module_name, MetricKind::Module,
              "time_since_last_any_receive_sec");
    addColumn(config_.module_name, MetricKind::Module, "dropped_sample_count");

    for (const auto& registered : registered_order_) {
      if (registered.kind == MetricKind::Header) {
        addHeaderColumns(registered.name);
      } else {
        addNumericColumns(registered.name, registered.kind);
      }
    }
  }

  void addHeaderColumns(const std::string& name) {
    addColumn(name, MetricKind::Header, "total_received_count");
    addColumn(name, MetricKind::Header, "total_lost_count");
    addColumn(name, MetricKind::Header, "loss_rate");
    addColumn(name, MetricKind::Header, "total_out_of_order_count");
    addColumn(name, MetricKind::Header, "latency_sec_min");
    addColumn(name, MetricKind::Header, "latency_sec_max");
    addColumn(name, MetricKind::Header, "latency_sec_avg");
    addColumn(name, MetricKind::Header, "frequency_hz");
    addColumn(name, MetricKind::Header, "last_sequence");
    addAvailabilityColumns(name, MetricKind::Header);
    addStatusColumns(name, MetricKind::Header);
  }

  void addNumericColumns(const std::string& name, MetricKind kind) {
    addColumn(name, kind, "total_count");
    addColumn(name, kind, "count");
    addColumn(name, kind, "min");
    addColumn(name, kind, "max");
    addColumn(name, kind, "avg");
    if (kind == MetricKind::Normal) {
      addColumn(name, kind, "variance");
      addColumn(name, kind, "stddev");
    } else {
      addColumn(name, kind, "worst_1_percent_avg");
    }
    addAvailabilityColumns(name, kind);
    addStatusColumns(name, kind);
  }

  void addAvailabilityColumns(const std::string& name, MetricKind kind) {
    addColumn(name, kind, "time_since_create_sec");
    addColumn(name, kind, "time_since_last_receive_sec");
  }

  void addStatusColumns(const std::string& name, MetricKind kind) {
    addColumn(name, kind, "status/ok");
    addColumn(name, kind, "status/warn");
    addColumn(name, kind, "status/error");
    addColumn(name, kind, "status/no_data");
    addColumn(name, kind, "status/data_lost");
  }

  void addColumn(const std::string& name, MetricKind kind,
                 const std::string& key) {
    Column column;
    column.metric_name = name;
    column.kind = kind;
    column.key = key;
    column.csv_name = sanitizeName(name) + "/" + key;
    metrics_columns_.push_back(std::move(column));
  }

  // Opens the all-metrics CSV and writes its fixed header.
  void openMetricsCsvLocked() {
    if (!config_.write_metrics_csv) {
      return;
    }
    const std::string path =
        config_.log_directory + "/" + base_file_stem_ + "_metrics.csv";
    metrics_csv_.open(path, std::ios::out | std::ios::trunc);
    if (!metrics_csv_) {
      internal_error_message_ = "failed to open metrics csv: " + path;
      return;
    }
    metrics_csv_ << "time";
    for (const auto& column : metrics_columns_) {
      metrics_csv_ << "," << column.csv_name;
    }
    metrics_csv_ << "\n";
    std::cout << "Created metrics CSV: " << absolutePath(path) << "\n";
  }

  // Opens one raw CSV file for every registered source.
  void openRawCsvFilesLocked() {
    if (!config_.write_raw_csv) {
      return;
    }
    for (const auto& registered : registered_order_) {
      const std::string path = config_.log_directory + "/" + base_file_stem_ +
                               "_" + sanitizeFileName(registered.name) +
                               "_raw.csv";
      RawCsvFile file;
      file.kind = registered.kind;
      file.stream.open(path, std::ios::out | std::ios::trunc);
      if (!file.stream) {
        internal_error_message_ = "failed to open raw csv: " + path;
        continue;
      }
      if (registered.kind == MetricKind::Header) {
        file.stream << "time,source_timestamp_sec,receive_time_sec,sequence,"
                       "latency_sec\n";
      } else {
        file.stream << "time,receive_time_sec,value\n";
      }
      std::cout << "Created raw CSV: " << absolutePath(path) << "\n";
      raw_csv_files_[registered.name] = std::move(file);
    }
  }

  void maybeAppendMetricsCsvRowLocked(double now) {
    if (now - last_metrics_csv_write_sec_ <
        config_.metrics_csv_write_interval_sec) {
      return;
    }
    appendMetricsCsvRowLocked(now);
    last_metrics_csv_write_sec_ = now;
  }

  void appendMetricsCsvRowLocked(double now) {
    if (!metrics_csv_) {
      return;
    }
    std::unordered_map<std::string, const MetricResult*> result_by_name;
    for (const auto& result : latest_results_cache_) {
      result_by_name[result.name] = &result;
    }

    metrics_csv_ << formatDouble(now);
    for (const auto& column : metrics_columns_) {
      double value = config_.missing_value;
      const auto it = result_by_name.find(column.metric_name);
      if (it != result_by_name.end()) {
        const MetricResult& result = *it->second;
        value = columnValue(result, column.key);
      }
      metrics_csv_ << "," << formatDouble(value);
    }
    metrics_csv_ << "\n";
  }

  // Status columns are encoded as 0/1 numeric signals for PlotJuggler.
  static double columnValue(const MetricResult& result,
                            const std::string& key) {
    if (key.rfind("status/", 0) == 0) {
      const std::string status = key.substr(std::string("status/").size());
      return status == toString(result.status) ? 1.0 : 0.0;
    }
    const auto it = result.values.find(key);
    return it == result.values.end() ? std::numeric_limits<double>::quiet_NaN()
                                     : it->second;
  }

  // Writes one actual raw header sample. The first column is time for
  // PlotJuggler; receive_time_sec is repeated explicitly for analysis.
  void appendHeaderRawSampleLocked(const std::string& name,
                                   const HeaderSample& sample) {
    if (!config_.write_raw_csv) {
      return;
    }
    auto it = raw_csv_files_.find(name);
    if (it == raw_csv_files_.end() || !it->second.stream) {
      return;
    }
    it->second.stream << formatDouble(sample.receive_time_sec) << ","
                      << formatDouble(sample.source_timestamp_sec) << ","
                      << formatDouble(sample.receive_time_sec) << ","
                      << sample.sequence << ","
                      << formatDouble(sample.receive_time_sec -
                                      sample.source_timestamp_sec)
                      << "\n";
  }

  // Writes one actual raw numeric sample for cost/score/normal streams.
  void appendNumericRawSampleLocked(const std::string& name,
                                    const NumericSample& sample) {
    if (!config_.write_raw_csv) {
      return;
    }
    auto it = raw_csv_files_.find(name);
    if (it == raw_csv_files_.end() || !it->second.stream) {
      return;
    }
    it->second.stream << formatDouble(sample.receive_time_sec) << ","
                      << formatDouble(sample.receive_time_sec) << ","
                      << formatDouble(sample.value) << "\n";
  }

  void maybeWriteTmpSnapshotFileLocked(double now) {
    if (now - last_tmp_snapshot_write_sec_ <
        config_.tmp_snapshot_write_interval_sec) {
      return;
    }
    writeTmpSnapshotFileLocked(now);
    last_tmp_snapshot_write_sec_ = now;
  }

  void writeTmpSnapshotFileLocked(double now) {
    if (!config_.write_tmp_json_snapshot) {
      return;
    }
    const std::string path = config_.snapshot_directory + "/" +
                             sanitizeFileName(config_.module_name) +
                             "_metrics_snapshot.json";
    const std::string tmp_path = path + ".tmp";
    std::ofstream out(tmp_path, std::ios::out | std::ios::trunc);
    if (!out) {
      internal_error_message_ = "failed to open tmp snapshot: " + tmp_path;
      return;
    }

    out << "{\n";
    out << "  \"module\": \"" << jsonEscape(config_.module_name) << "\",\n";
    out << "  \"wall_time_sec\": " << formatJsonNumber(now) << ",\n";
    out << "  \"results\": [\n";
    for (std::size_t i = 0; i < latest_results_cache_.size(); ++i) {
      const auto& result = latest_results_cache_[i];
      out << "    {\n";
      out << "      \"name\": \"" << jsonEscape(result.name) << "\",\n";
      out << "      \"kind\": \"" << toString(result.kind) << "\",\n";
      out << "      \"status\": \"" << toString(result.status) << "\",\n";
      out << "      \"message\": \"" << jsonEscape(result.message) << "\",\n";
      out << "      \"values\": {\n";
      std::size_t idx = 0;
      for (const auto& kv : result.values) {
        out << "        \"" << jsonEscape(kv.first)
            << "\": " << formatJsonNumber(kv.second);
        if (++idx < result.values.size()) {
          out << ",";
        }
        out << "\n";
      }
      out << "      }\n";
      out << "    }";
      if (i + 1 < latest_results_cache_.size()) {
        out << ",";
      }
      out << "\n";
    }
    out << "  ]\n";
    out << "}\n";
    out.close();
    // Rename gives readers either the previous complete snapshot or the new
    // complete snapshot on typical POSIX filesystems.
    std::rename(tmp_path.c_str(), path.c_str());
  }

  // Called at shutdown; normal periodic writes are intentionally not flushed on
  // every row to keep I/O overhead low.
  void flushFiles() {
    std::lock_guard<std::mutex> lock(state_mutex_);
    if (metrics_csv_) {
      metrics_csv_.flush();
    }
    for (auto& item : raw_csv_files_) {
      if (item.second.stream) {
        item.second.stream.flush();
      }
    }
  }

  // Immutable-after-construction user settings, except clock_now_sec may be
  // filled with the default clock in the constructor.
  MetricMonitorConfig config_;

  // Worker lifecycle.
  std::atomic<bool> running_{false};
  std::thread worker_;

  // Producer/consumer queue. record*() holds queue_mutex_ briefly; the worker
  // drains the queue into a local batch before taking state_mutex_.
  mutable std::mutex queue_mutex_;
  std::condition_variable queue_cv_;
  std::deque<QueuedSample> pending_samples_;
  std::atomic<std::uint64_t> dropped_sample_count_{0};

  // Metric states and file writers are owned by the worker thread while
  // state_mutex_ is held. Registration/finalize also use this mutex.
  mutable std::mutex state_mutex_;
  bool finalized_ = false;
  double created_time_sec_ = 0.0;
  bool has_received_any_data_ = false;
  double last_any_receive_time_sec_ = 0.0;

  // Registered streams define fixed CSV schemas. Late auto-created streams are
  // still processed, but do not get fixed CSV columns/raw files.
  std::vector<RegisteredMetric> registered_order_;
  std::unordered_map<std::string, HeaderMetricState> header_states_;
  std::unordered_map<std::string, NumericMetricState> numeric_states_;

  // latest_results_ is the public copy. latest_results_cache_ is the worker's
  // private copy used for CSV/JSON output without taking results_mutex_ again.
  mutable std::mutex results_mutex_;
  std::vector<MetricResult> latest_results_;
  std::vector<MetricResult> latest_results_cache_;

  // Output files and fixed schema generated by finalizeSchema().
  std::string base_file_stem_;
  std::vector<Column> metrics_columns_;
  std::ofstream metrics_csv_;
  std::unordered_map<std::string, RawCsvFile> raw_csv_files_;

  // Periodic output timestamps.
  double last_metrics_csv_write_sec_ = 0.0;
  double last_tmp_snapshot_write_sec_ = 0.0;

  // Last internal I/O error. Currently retained for debugging/extension.
  std::string internal_error_message_;
};

}  // namespace metric_monitor
